name: Question
description: Ask for support or start a discussion about DOSBox-X
labels: question

body:
  - type: checkboxes
    id: alreadyexists
    attributes:
      label: Have you checked that no similar question(s) exist?
      description: Please try to search for similar questions in the issues before creating this issue.
      options:
        - label: I have searched and didn't find any similar question.
          required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: A clear and concise description of what your question is. If applicable, add screenshots to help in explaining.
      placeholder: "Ex. How do I [...]"
    validations:
      required: true