name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        include:
        - configuration: Debug
          cache-version: 2
        - configuration: Release
          cache-version: 2

    name: Build (${{ matrix.configuration }})
    runs-on: windows-latest

    env:
      Solution_Name: HATE.sln
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Cache build objects
      uses: actions/cache@v3
      with:
        path: |
          HATE/bin/${{ matrix.configuration }}
          HATE/obj/${{ matrix.configuration }}
          UndertaleModTool/UndertaleModLib/bin/${{ matrix.configuration }}
          UndertaleModTool/UndertaleModLib/obj/${{ matrix.configuration }}
          C:\Program Files (x86)\Microsoft SDKs\NuGetPackages
        key: ${{ runner.os }}-${{ matrix.configuration }}-objs-v${{ matrix.cache-version }}

    - name: Restore
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /t:Restore

    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:NoWarn="1591;1574;"
