name: Build

on:
  push:
  pull_request:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: HATE.sln
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration

    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
