name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    env:
      cache-version: 3

    name: Build (${{ matrix.configuration }})
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore
      run: dotnet restore

    - name: Build
      run: |
        dotnet build HATE.WinForms --no-restore
        dotnet build HATE.Gtk --no-restore
    - name: Publish
      run: |
        dotnet publish HATE.WinForms -c ${{ matrix.configuration }} -r win-x64 --no-self-contained
        dotnet publish HATE.Gtk -c ${{ matrix.configuration }} -r linux-x64 --no-self-contained
